### ISSUE TITLE
Not working on Firefox and Safari

### ISSUE THREAD

**Issue by loyalty1puneet** [hboylan/react-bot-ui#1]
Your react-bot-ui npm module is not working in Firefox and Safari.
Request you to please look into it as your module is very helpful for many people.

Getting the bellow errors:

> TypeError: SpeechRecognition is not a constructor
> TypeError: Not enough arguments to EventTarget.removeEventListener.

Really appreciate your help.

**Comment by hboylan** [comment]
This is related to the SpeechRecognition API, which is not yet integrated with Firefox/Safari.

If you'd like to help everyone out, take a look at [`src/components/Audio.js`](https://github.com/hboylan/react-bot-ui/blob/5755d53/src/components/Audio.js#L4) and check for compatibility before calling the SpeechRecognition constructor.

**Comment by loyalty1puneet** [comment]
Sure, I'll try to look into it.
Just wondering if we should comment out Audio part of it for now. I mean we can use your module for text only without speech capabilities so that at least it is in production ready stage for all the browsers.

**Comment by hboylan** [comment]
I agree. It will be a great feature for accessibility, but still needs work before being fully integrated with this component.

I would leave `Audio.js` alone for now and instead comment out the places it's used inside [`src/components/Input.js`](https://github.com/hboylan/react-bot-ui/blob/56dee38/src/components/Input.js#L42).
