### ISSUE TITLE
Is this module still available?

### ISSUE THREAD

**Issue by jamiecoe** [hboylan/react-bot-ui#3]
Hi,

I'm working on a chatbot app using Dialog Flow. My team are keen to use React on the front-end and this module looks great! However it seems to be no longer available on NPM 😢? 

Also, is it possible to have buttons displayed on the front-end?

Cheers!

**Comment by loyalty1puneet** [comment]
Hi,

I believe you can still install the package using specific version ^1.0.5
e.g. npm install react-bot-ui@1.0.5

However this deems to be breaking version since css is set at global level.
Workaround is to delete css in node_modules and use locally in your application.

Cheers.

**Comment by jamiecoe** [comment]
Thanks @loyalty1puneet! 

My team is building a chatbot for a small UK charity, [Chayn](https://chayn.co/). Is the license for this module open source (eg: [MIT License](https://opensource.org/licenses/MIT))? If so, would it be possible to add this to the README?

**Comment by jamiecoe** [comment]
Ah I've spotted it's got an ISC license on the [NPM page](https://www.npmjs.com/package/react-bot-ui). So I assume it's fine to use in our project.

**Comment by hboylan** [comment]
Hey guys, sorry I'm no longer able to support this project. :cry: 

It was a prototype for a client so I eventually had to migrate to their private repo. Feel free to use what you already have, but I'll be deleting this repository soon.
